[package]
name = "badlog"
version = "0.1.1"
description = "A simple zero customization, colored logger."
license = "MIT"
repository = "https://github.com/quadrupleslap/badlog"
authors = ["Ram Kaniyur <quadrupleslap@gmail.com>"]

[dependencies]
env_logger = "0.4.0"
log = "0.3"
ansi_term = "0.9"
